services:
  postgresql:
    container_name: 'meucontainer'
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: minhasenha
      POSTGRES_DB: meu_banco
    ports:
      - "5433:5432"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "seuemail@email.com"
      PGADMIN_DEFAULT_PASSWORD: "senha1"
    ports:
      - "8090:80"
    depends_on:
      - postgresql
  api:
    container_name: 'sorteio_online_api'
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgresql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/meu_banco